# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MonitorForm(object):
    def setupUi(self, MonitorForm):
        MonitorForm.setObjectName("MonitorForm")
        MonitorForm.resize(1050, 580)
        MonitorForm.setMinimumSize(QtCore.QSize(1050, 580))
        MonitorForm.setMaximumSize(QtCore.QSize(1050, 580))
        self.tabWidget = QtWidgets.QTabWidget(MonitorForm)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1041, 581))
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.groupBox_1 = QtWidgets.QGroupBox(self.tab1)
        self.groupBox_1.setGeometry(QtCore.QRect(10, 10, 231, 241))
        self.groupBox_1.setFlat(False)
        self.groupBox_1.setObjectName("groupBox_1")
        self.mute1 = QtWidgets.QCheckBox(self.groupBox_1)
        self.mute1.setGeometry(QtCore.QRect(20, 100, 85, 21))
        self.mute1.setObjectName("mute1")
        self.label = QtWidgets.QLabel(self.groupBox_1)
        self.label.setGeometry(QtCore.QRect(20, 60, 61, 20))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_1)
        self.label_2.setGeometry(QtCore.QRect(20, 130, 91, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.info1 = QtWidgets.QPlainTextEdit(self.groupBox_1)
        self.info1.setGeometry(QtCore.QRect(20, 150, 191, 70))
        self.info1.setObjectName("info1")
        self.vol1 = QtWidgets.QSlider(self.groupBox_1)
        self.vol1.setGeometry(QtCore.QRect(20, 80, 191, 16))
        self.vol1.setOrientation(QtCore.Qt.Horizontal)
        self.vol1.setObjectName("vol1")
        self.label_3 = QtWidgets.QLabel(self.groupBox_1)
        self.label_3.setGeometry(QtCore.QRect(20, 40, 51, 16))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.status1 = QtWidgets.QLineEdit(self.groupBox_1)
        self.status1.setGeometry(QtCore.QRect(70, 40, 141, 23))
        self.status1.setReadOnly(True)
        self.status1.setObjectName("status1")
        self.pbReset1 = QtWidgets.QPushButton(self.groupBox_1)
        self.pbReset1.setGeometry(QtCore.QRect(140, 100, 71, 23))
        self.pbReset1.setObjectName("pbReset1")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab1)
        self.groupBox_2.setGeometry(QtCore.QRect(270, 10, 231, 241))
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.mute2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.mute2.setGeometry(QtCore.QRect(20, 100, 85, 21))
        self.mute2.setObjectName("mute2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 60, 61, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(20, 130, 91, 16))
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.info2 = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.info2.setGeometry(QtCore.QRect(20, 150, 191, 70))
        self.info2.setObjectName("info2")
        self.vol2 = QtWidgets.QSlider(self.groupBox_2)
        self.vol2.setGeometry(QtCore.QRect(20, 80, 191, 16))
        self.vol2.setOrientation(QtCore.Qt.Horizontal)
        self.vol2.setObjectName("vol2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(20, 40, 51, 16))
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.status2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.status2.setGeometry(QtCore.QRect(70, 40, 141, 23))
        self.status2.setReadOnly(True)
        self.status2.setObjectName("status2")
        self.pbReset2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pbReset2.setGeometry(QtCore.QRect(140, 100, 71, 23))
        self.pbReset2.setObjectName("pbReset2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab1)
        self.groupBox_3.setGeometry(QtCore.QRect(530, 10, 231, 241))
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.mute3 = QtWidgets.QCheckBox(self.groupBox_3)
        self.mute3.setGeometry(QtCore.QRect(20, 100, 85, 21))
        self.mute3.setObjectName("mute3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(20, 60, 61, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(20, 130, 91, 16))
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.info3 = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.info3.setGeometry(QtCore.QRect(20, 150, 191, 70))
        self.info3.setObjectName("info3")
        self.vol3 = QtWidgets.QSlider(self.groupBox_3)
        self.vol3.setGeometry(QtCore.QRect(20, 80, 191, 16))
        self.vol3.setOrientation(QtCore.Qt.Horizontal)
        self.vol3.setObjectName("vol3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(20, 40, 51, 16))
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.status3 = QtWidgets.QLineEdit(self.groupBox_3)
        self.status3.setGeometry(QtCore.QRect(70, 40, 141, 23))
        self.status3.setReadOnly(True)
        self.status3.setObjectName("status3")
        self.pbReset3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pbReset3.setGeometry(QtCore.QRect(140, 100, 71, 23))
        self.pbReset3.setObjectName("pbReset3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab1)
        self.groupBox_4.setGeometry(QtCore.QRect(790, 10, 231, 241))
        self.groupBox_4.setFlat(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.mute4 = QtWidgets.QCheckBox(self.groupBox_4)
        self.mute4.setGeometry(QtCore.QRect(20, 100, 85, 21))
        self.mute4.setObjectName("mute4")
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setGeometry(QtCore.QRect(20, 60, 61, 20))
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setGeometry(QtCore.QRect(20, 130, 91, 16))
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.info4 = QtWidgets.QPlainTextEdit(self.groupBox_4)
        self.info4.setGeometry(QtCore.QRect(20, 150, 191, 70))
        self.info4.setObjectName("info4")
        self.vol4 = QtWidgets.QSlider(self.groupBox_4)
        self.vol4.setGeometry(QtCore.QRect(20, 80, 191, 16))
        self.vol4.setOrientation(QtCore.Qt.Horizontal)
        self.vol4.setObjectName("vol4")
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setGeometry(QtCore.QRect(20, 40, 51, 16))
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.status4 = QtWidgets.QLineEdit(self.groupBox_4)
        self.status4.setGeometry(QtCore.QRect(70, 40, 141, 23))
        self.status4.setReadOnly(True)
        self.status4.setObjectName("status4")
        self.pbReset4 = QtWidgets.QPushButton(self.groupBox_4)
        self.pbReset4.setGeometry(QtCore.QRect(140, 100, 71, 23))
        self.pbReset4.setObjectName("pbReset4")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab1)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 300, 231, 241))
        self.groupBox_6.setFlat(False)
        self.groupBox_6.setObjectName("groupBox_6")
        self.mute5 = QtWidgets.QCheckBox(self.groupBox_6)
        self.mute5.setGeometry(QtCore.QRect(20, 100, 85, 21))
        self.mute5.setObjectName("mute5")
        self.label_13 = QtWidgets.QLabel(self.groupBox_6)
        self.label_13.setGeometry(QtCore.QRect(20, 60, 61, 20))
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_6)
        self.label_14.setGeometry(QtCore.QRect(20, 130, 91, 16))
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.info5 = QtWidgets.QPlainTextEdit(self.groupBox_6)
        self.info5.setGeometry(QtCore.QRect(20, 150, 191, 70))
        self.info5.setObjectName("info5")
        self.vol5 = QtWidgets.QSlider(self.groupBox_6)
        self.vol5.setGeometry(QtCore.QRect(20, 80, 191, 16))
        self.vol5.setOrientation(QtCore.Qt.Horizontal)
        self.vol5.setObjectName("vol5")
        self.label_15 = QtWidgets.QLabel(self.groupBox_6)
        self.label_15.setGeometry(QtCore.QRect(20, 40, 51, 16))
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.status5 = QtWidgets.QLineEdit(self.groupBox_6)
        self.status5.setGeometry(QtCore.QRect(70, 40, 141, 23))
        self.status5.setReadOnly(True)
        self.status5.setObjectName("status5")
        self.pbReset5 = QtWidgets.QPushButton(self.groupBox_6)
        self.pbReset5.setGeometry(QtCore.QRect(140, 100, 71, 23))
        self.pbReset5.setObjectName("pbReset5")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab1)
        self.groupBox_7.setGeometry(QtCore.QRect(270, 300, 231, 241))
        self.groupBox_7.setFlat(False)
        self.groupBox_7.setObjectName("groupBox_7")
        self.mute6 = QtWidgets.QCheckBox(self.groupBox_7)
        self.mute6.setGeometry(QtCore.QRect(20, 100, 85, 21))
        self.mute6.setObjectName("mute6")
        self.label_16 = QtWidgets.QLabel(self.groupBox_7)
        self.label_16.setGeometry(QtCore.QRect(20, 60, 61, 20))
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_7)
        self.label_17.setGeometry(QtCore.QRect(20, 130, 91, 16))
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.info6 = QtWidgets.QPlainTextEdit(self.groupBox_7)
        self.info6.setGeometry(QtCore.QRect(20, 150, 191, 70))
        self.info6.setObjectName("info6")
        self.vol6 = QtWidgets.QSlider(self.groupBox_7)
        self.vol6.setGeometry(QtCore.QRect(20, 80, 191, 16))
        self.vol6.setOrientation(QtCore.Qt.Horizontal)
        self.vol6.setObjectName("vol6")
        self.label_18 = QtWidgets.QLabel(self.groupBox_7)
        self.label_18.setGeometry(QtCore.QRect(20, 40, 51, 16))
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.status6 = QtWidgets.QLineEdit(self.groupBox_7)
        self.status6.setGeometry(QtCore.QRect(70, 40, 141, 23))
        self.status6.setReadOnly(True)
        self.status6.setObjectName("status6")
        self.pbReset6 = QtWidgets.QPushButton(self.groupBox_7)
        self.pbReset6.setGeometry(QtCore.QRect(140, 100, 71, 23))
        self.pbReset6.setObjectName("pbReset6")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab1)
        self.groupBox_8.setGeometry(QtCore.QRect(530, 300, 231, 241))
        self.groupBox_8.setFlat(False)
        self.groupBox_8.setObjectName("groupBox_8")
        self.mute7 = QtWidgets.QCheckBox(self.groupBox_8)
        self.mute7.setGeometry(QtCore.QRect(20, 100, 85, 21))
        self.mute7.setObjectName("mute7")
        self.label_19 = QtWidgets.QLabel(self.groupBox_8)
        self.label_19.setGeometry(QtCore.QRect(20, 60, 61, 20))
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_8)
        self.label_20.setGeometry(QtCore.QRect(20, 130, 91, 16))
        self.label_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.info7 = QtWidgets.QPlainTextEdit(self.groupBox_8)
        self.info7.setGeometry(QtCore.QRect(20, 150, 191, 70))
        self.info7.setObjectName("info7")
        self.vol7 = QtWidgets.QSlider(self.groupBox_8)
        self.vol7.setGeometry(QtCore.QRect(20, 80, 191, 16))
        self.vol7.setOrientation(QtCore.Qt.Horizontal)
        self.vol7.setObjectName("vol7")
        self.label_21 = QtWidgets.QLabel(self.groupBox_8)
        self.label_21.setGeometry(QtCore.QRect(20, 40, 51, 16))
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.status7 = QtWidgets.QLineEdit(self.groupBox_8)
        self.status7.setGeometry(QtCore.QRect(70, 40, 141, 23))
        self.status7.setReadOnly(True)
        self.status7.setObjectName("status7")
        self.pbReset7 = QtWidgets.QPushButton(self.groupBox_8)
        self.pbReset7.setGeometry(QtCore.QRect(140, 100, 71, 23))
        self.pbReset7.setObjectName("pbReset7")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab1)
        self.groupBox_9.setGeometry(QtCore.QRect(790, 300, 231, 241))
        self.groupBox_9.setFlat(False)
        self.groupBox_9.setObjectName("groupBox_9")
        self.mute8 = QtWidgets.QCheckBox(self.groupBox_9)
        self.mute8.setGeometry(QtCore.QRect(20, 100, 85, 21))
        self.mute8.setObjectName("mute8")
        self.label_22 = QtWidgets.QLabel(self.groupBox_9)
        self.label_22.setGeometry(QtCore.QRect(20, 60, 61, 20))
        self.label_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_9)
        self.label_23.setGeometry(QtCore.QRect(20, 130, 91, 16))
        self.label_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.info8 = QtWidgets.QPlainTextEdit(self.groupBox_9)
        self.info8.setGeometry(QtCore.QRect(20, 150, 191, 70))
        self.info8.setObjectName("info8")
        self.vol8 = QtWidgets.QSlider(self.groupBox_9)
        self.vol8.setGeometry(QtCore.QRect(20, 80, 191, 16))
        self.vol8.setOrientation(QtCore.Qt.Horizontal)
        self.vol8.setObjectName("vol8")
        self.label_24 = QtWidgets.QLabel(self.groupBox_9)
        self.label_24.setGeometry(QtCore.QRect(20, 40, 51, 16))
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.status8 = QtWidgets.QLineEdit(self.groupBox_9)
        self.status8.setGeometry(QtCore.QRect(70, 40, 141, 23))
        self.status8.setReadOnly(True)
        self.status8.setObjectName("status8")
        self.pbReset8 = QtWidgets.QPushButton(self.groupBox_9)
        self.pbReset8.setGeometry(QtCore.QRect(140, 100, 71, 23))
        self.pbReset8.setObjectName("pbReset8")
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab2)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 0, 1021, 541))
        self.groupBox_5.setObjectName("groupBox_5")
        self.dbgConsole = QtWidgets.QPlainTextEdit(self.groupBox_5)
        self.dbgConsole.setGeometry(QtCore.QRect(0, 20, 1021, 531))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.dbgConsole.setPalette(palette)
        self.dbgConsole.setObjectName("dbgConsole")
        self.tabWidget.addTab(self.tab2, "")

        self.retranslateUi(MonitorForm)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MonitorForm)

    def retranslateUi(self, MonitorForm):
        _translate = QtCore.QCoreApplication.translate
        MonitorForm.setWindowTitle(_translate("MonitorForm", "Monitoring Dashboard"))
        self.groupBox_1.setTitle(_translate("MonitorForm", "Station-1"))
        self.mute1.setText(_translate("MonitorForm", "Mute"))
        self.label.setText(_translate("MonitorForm", "Volume"))
        self.label_2.setText(_translate("MonitorForm", "Info Location:"))
        self.label_3.setText(_translate("MonitorForm", "Status:"))
        self.pbReset1.setText(_translate("MonitorForm", "Reset"))
        self.groupBox_2.setTitle(_translate("MonitorForm", "Station-2"))
        self.mute2.setText(_translate("MonitorForm", "Mute"))
        self.label_4.setText(_translate("MonitorForm", "Volume"))
        self.label_5.setText(_translate("MonitorForm", "Info Location:"))
        self.label_6.setText(_translate("MonitorForm", "Status:"))
        self.pbReset2.setText(_translate("MonitorForm", "Reset"))
        self.groupBox_3.setTitle(_translate("MonitorForm", "Station-3"))
        self.mute3.setText(_translate("MonitorForm", "Mute"))
        self.label_7.setText(_translate("MonitorForm", "Volume"))
        self.label_8.setText(_translate("MonitorForm", "Info Location:"))
        self.label_9.setText(_translate("MonitorForm", "Status:"))
        self.pbReset3.setText(_translate("MonitorForm", "Reset"))
        self.groupBox_4.setTitle(_translate("MonitorForm", "Station-4"))
        self.mute4.setText(_translate("MonitorForm", "Mute"))
        self.label_10.setText(_translate("MonitorForm", "Volume"))
        self.label_11.setText(_translate("MonitorForm", "Info Location:"))
        self.label_12.setText(_translate("MonitorForm", "Status:"))
        self.pbReset4.setText(_translate("MonitorForm", "Reset"))
        self.groupBox_6.setTitle(_translate("MonitorForm", "Station-5"))
        self.mute5.setText(_translate("MonitorForm", "Mute"))
        self.label_13.setText(_translate("MonitorForm", "Volume"))
        self.label_14.setText(_translate("MonitorForm", "Info Location:"))
        self.label_15.setText(_translate("MonitorForm", "Status:"))
        self.pbReset5.setText(_translate("MonitorForm", "Reset"))
        self.groupBox_7.setTitle(_translate("MonitorForm", "Station-6"))
        self.mute6.setText(_translate("MonitorForm", "Mute"))
        self.label_16.setText(_translate("MonitorForm", "Volume"))
        self.label_17.setText(_translate("MonitorForm", "Info Location:"))
        self.label_18.setText(_translate("MonitorForm", "Status:"))
        self.pbReset6.setText(_translate("MonitorForm", "Reset"))
        self.groupBox_8.setTitle(_translate("MonitorForm", "Station-7"))
        self.mute7.setText(_translate("MonitorForm", "Mute"))
        self.label_19.setText(_translate("MonitorForm", "Volume"))
        self.label_20.setText(_translate("MonitorForm", "Info Location:"))
        self.label_21.setText(_translate("MonitorForm", "Status:"))
        self.pbReset7.setText(_translate("MonitorForm", "Reset"))
        self.groupBox_9.setTitle(_translate("MonitorForm", "Station-8"))
        self.mute8.setText(_translate("MonitorForm", "Mute"))
        self.label_22.setText(_translate("MonitorForm", "Volume"))
        self.label_23.setText(_translate("MonitorForm", "Info Location:"))
        self.label_24.setText(_translate("MonitorForm", "Status:"))
        self.pbReset8.setText(_translate("MonitorForm", "Reset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MonitorForm", "Main Controller"))
        self.groupBox_5.setTitle(_translate("MonitorForm", "Debugging"))
        self.dbgConsole.setPlainText(_translate("MonitorForm", "Apapun yang terjadi dengan sistem bisa diinformasikan dalam debug console ini!"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("MonitorForm", "Aux"))

